"""empty message

Revision ID: 10fb9e01cb17
Revises: 7ed4ad3e8761
Create Date: 2025-04-29 22:30:23.670142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10fb9e01cb17'
down_revision = '7ed4ad3e8761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_follow', ['follower_id', 'followed_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follower', schema=None) as batch_op:
        batch_op.drop_constraint('unique_follow', type_='unique')

    # ### end Alembic commands ###
